include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Sorting list of pub dependencies is annoy.
    sort_pub_dependencies: false

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # print is also a function
    avoid_print: false

    # Allow to use Container
    avoid_unnecessary_containers: false

    unnecessary_await_in_return: false

    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors: false
    sized_box_for_whitespace: false
    avoid_positional_boolean_parameters: false

    # To prevent warnings in generated files
    # prefer_final_locals: false
    type_annotate_public_apis: false
